print ('\033[1;32m*')
print ('\033[1;32m_   _')
print ('\033[1;32m| | | | ___  __ _  __ _ _____   _')
print ('\033[1;33m| |_| |/ _ \/ _` |/ _` |_  / | | |')
print ('\033[1;34m|  _  |  __/ (_| | (_| |/ /| |_| |')
print ('\033[1;35m|_| |_|\___|\__, |\__,_/___|\__, |')
print ('\033[1;35m            |___/           |___/')
print ('\033[1;32m*')
print ('Welcome to <<ahmedhegazy>> Tool')
print ('*')
print ('\033[1;35mhttps://linktr.ee/ahmedhegazy')
print ('*')
print ('\033[1;34m1_')
print ('The first commands to run Termux before starting')
print ('*')
print ('\033[1;33mpkg update')
print ('pkg upgrade')
print ('pkg install python')
print ('pkg install python2')
print ('pkg install python3')
print ('pkg install ruby')
print ('pkg install git')
print ('pkg install php')
print ('pkg install java')
print ('Pkg install google')
print ('pkg install bash')
print ('pkg install perl')
print ('pkg install nmap')
print ('pkg install bash')
print ('pkg install clang')
print ('pkg install macchanger')
print ('pkg install nano')
print ('pkg install figlet')
print ('pkg install cowsay')
print ('pkg install curl')
print ('pkg install tar')
print ('pkg install zip')
print ('pkg install unzip')
print ('pkg install tor')
print ('pkg install sudo')
print ('pkg install wget')
print ('pkg install wcalc')
print ('pkg install openssl')
print ('pkg install bmon')
print ('*')
print ('\033[1;31mCopy it like this and place it in the tremux, and it will automatically install')
print ('*')
